colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
firebase = { }
fathomAnalytics = { }
verification = { }
defaultBackgroundImage = "DJI_0066.jpg"
defaultFeaturedImage = "Rust.jpg"

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true
showMenu = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "9"
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "Rust.jpg"

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "thumbAndBackground"
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = true
layoutBackgroundHeaderSpace = "200"

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = [ ]

[taxonomy]
showTermCount = true
